package com.ywjs.mapper;

import com.ywjs.model.entity.EletypeProperty;
import com.ywjs.model.entity.EletypePropertyExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EletypePropertyMapper {
    
    List<EletypeProperty> selectAll();
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELETYPE_PROPERTY_TBL
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    int countByExample(EletypePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELETYPE_PROPERTY_TBL
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    int deleteByExample(EletypePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELETYPE_PROPERTY_TBL
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    int deleteByPrimaryKey(Integer eleproidElepro);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELETYPE_PROPERTY_TBL
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    int insert(EletypeProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELETYPE_PROPERTY_TBL
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    int insertSelective(EletypeProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELETYPE_PROPERTY_TBL
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    List<EletypeProperty> selectByExample(EletypePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELETYPE_PROPERTY_TBL
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    EletypeProperty selectByPrimaryKey(Integer eleproidElepro);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELETYPE_PROPERTY_TBL
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") EletypeProperty record, @Param("example") EletypePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELETYPE_PROPERTY_TBL
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    int updateByExample(@Param("record") EletypeProperty record, @Param("example") EletypePropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELETYPE_PROPERTY_TBL
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    int updateByPrimaryKeySelective(EletypeProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELETYPE_PROPERTY_TBL
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    int updateByPrimaryKey(EletypeProperty record);
}