package com.ywjs.mapper;

import com.ywjs.model.entity.PropertyValue;
import com.ywjs.model.entity.PropertyValueExample;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PropertyValueMapper {
    
    void insertBatch(List<PropertyValue> list);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROPERTY_VALUE_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    int countByExample(PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROPERTY_VALUE_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    int deleteByExample(PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROPERTY_VALUE_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    int deleteByPrimaryKey(Integer provalueidProval);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROPERTY_VALUE_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    int insert(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROPERTY_VALUE_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    int insertSelective(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROPERTY_VALUE_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    List<PropertyValue> selectByExample(PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROPERTY_VALUE_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    PropertyValue selectByPrimaryKey(Integer provalueidProval);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROPERTY_VALUE_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    int updateByExampleSelective(@Param("record") PropertyValue record, @Param("example") PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROPERTY_VALUE_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    int updateByExample(@Param("record") PropertyValue record, @Param("example") PropertyValueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROPERTY_VALUE_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    int updateByPrimaryKeySelective(PropertyValue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROPERTY_VALUE_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    int updateByPrimaryKey(PropertyValue record);
}