package com.ywjs.model.entity;

import java.util.ArrayList;
import java.util.List;

public class ElementExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ELEMENT_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ELEMENT_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ELEMENT_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELEMENT_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    public ElementExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELEMENT_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELEMENT_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELEMENT_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELEMENT_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELEMENT_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELEMENT_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELEMENT_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELEMENT_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELEMENT_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELEMENT_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ELEMENT_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andElementidEleIsNull() {
            addCriterion("ELEMENTID_ELE is null");
            return (Criteria) this;
        }

        public Criteria andElementidEleIsNotNull() {
            addCriterion("ELEMENTID_ELE is not null");
            return (Criteria) this;
        }

        public Criteria andElementidEleEqualTo(Integer value) {
            addCriterion("ELEMENTID_ELE =", value, "elementidEle");
            return (Criteria) this;
        }

        public Criteria andElementidEleNotEqualTo(Integer value) {
            addCriterion("ELEMENTID_ELE <>", value, "elementidEle");
            return (Criteria) this;
        }

        public Criteria andElementidEleGreaterThan(Integer value) {
            addCriterion("ELEMENTID_ELE >", value, "elementidEle");
            return (Criteria) this;
        }

        public Criteria andElementidEleGreaterThanOrEqualTo(Integer value) {
            addCriterion("ELEMENTID_ELE >=", value, "elementidEle");
            return (Criteria) this;
        }

        public Criteria andElementidEleLessThan(Integer value) {
            addCriterion("ELEMENTID_ELE <", value, "elementidEle");
            return (Criteria) this;
        }

        public Criteria andElementidEleLessThanOrEqualTo(Integer value) {
            addCriterion("ELEMENTID_ELE <=", value, "elementidEle");
            return (Criteria) this;
        }

        public Criteria andElementidEleIn(List<Integer> values) {
            addCriterion("ELEMENTID_ELE in", values, "elementidEle");
            return (Criteria) this;
        }

        public Criteria andElementidEleNotIn(List<Integer> values) {
            addCriterion("ELEMENTID_ELE not in", values, "elementidEle");
            return (Criteria) this;
        }

        public Criteria andElementidEleBetween(Integer value1, Integer value2) {
            addCriterion("ELEMENTID_ELE between", value1, value2, "elementidEle");
            return (Criteria) this;
        }

        public Criteria andElementidEleNotBetween(Integer value1, Integer value2) {
            addCriterion("ELEMENTID_ELE not between", value1, value2, "elementidEle");
            return (Criteria) this;
        }

        public Criteria andNodestarEleIsNull() {
            addCriterion("NODESTAR_ELE is null");
            return (Criteria) this;
        }

        public Criteria andNodestarEleIsNotNull() {
            addCriterion("NODESTAR_ELE is not null");
            return (Criteria) this;
        }

        public Criteria andNodestarEleEqualTo(String value) {
            addCriterion("NODESTAR_ELE =", value, "nodestarEle");
            return (Criteria) this;
        }

        public Criteria andNodestarEleNotEqualTo(String value) {
            addCriterion("NODESTAR_ELE <>", value, "nodestarEle");
            return (Criteria) this;
        }

        public Criteria andNodestarEleGreaterThan(String value) {
            addCriterion("NODESTAR_ELE >", value, "nodestarEle");
            return (Criteria) this;
        }

        public Criteria andNodestarEleGreaterThanOrEqualTo(String value) {
            addCriterion("NODESTAR_ELE >=", value, "nodestarEle");
            return (Criteria) this;
        }

        public Criteria andNodestarEleLessThan(String value) {
            addCriterion("NODESTAR_ELE <", value, "nodestarEle");
            return (Criteria) this;
        }

        public Criteria andNodestarEleLessThanOrEqualTo(String value) {
            addCriterion("NODESTAR_ELE <=", value, "nodestarEle");
            return (Criteria) this;
        }

        public Criteria andNodestarEleLike(String value) {
            addCriterion("NODESTAR_ELE like", value, "nodestarEle");
            return (Criteria) this;
        }

        public Criteria andNodestarEleNotLike(String value) {
            addCriterion("NODESTAR_ELE not like", value, "nodestarEle");
            return (Criteria) this;
        }

        public Criteria andNodestarEleIn(List<String> values) {
            addCriterion("NODESTAR_ELE in", values, "nodestarEle");
            return (Criteria) this;
        }

        public Criteria andNodestarEleNotIn(List<String> values) {
            addCriterion("NODESTAR_ELE not in", values, "nodestarEle");
            return (Criteria) this;
        }

        public Criteria andNodestarEleBetween(String value1, String value2) {
            addCriterion("NODESTAR_ELE between", value1, value2, "nodestarEle");
            return (Criteria) this;
        }

        public Criteria andNodestarEleNotBetween(String value1, String value2) {
            addCriterion("NODESTAR_ELE not between", value1, value2, "nodestarEle");
            return (Criteria) this;
        }

        public Criteria andNodeendEleIsNull() {
            addCriterion("NODEEND_ELE is null");
            return (Criteria) this;
        }

        public Criteria andNodeendEleIsNotNull() {
            addCriterion("NODEEND_ELE is not null");
            return (Criteria) this;
        }

        public Criteria andNodeendEleEqualTo(String value) {
            addCriterion("NODEEND_ELE =", value, "nodeendEle");
            return (Criteria) this;
        }

        public Criteria andNodeendEleNotEqualTo(String value) {
            addCriterion("NODEEND_ELE <>", value, "nodeendEle");
            return (Criteria) this;
        }

        public Criteria andNodeendEleGreaterThan(String value) {
            addCriterion("NODEEND_ELE >", value, "nodeendEle");
            return (Criteria) this;
        }

        public Criteria andNodeendEleGreaterThanOrEqualTo(String value) {
            addCriterion("NODEEND_ELE >=", value, "nodeendEle");
            return (Criteria) this;
        }

        public Criteria andNodeendEleLessThan(String value) {
            addCriterion("NODEEND_ELE <", value, "nodeendEle");
            return (Criteria) this;
        }

        public Criteria andNodeendEleLessThanOrEqualTo(String value) {
            addCriterion("NODEEND_ELE <=", value, "nodeendEle");
            return (Criteria) this;
        }

        public Criteria andNodeendEleLike(String value) {
            addCriterion("NODEEND_ELE like", value, "nodeendEle");
            return (Criteria) this;
        }

        public Criteria andNodeendEleNotLike(String value) {
            addCriterion("NODEEND_ELE not like", value, "nodeendEle");
            return (Criteria) this;
        }

        public Criteria andNodeendEleIn(List<String> values) {
            addCriterion("NODEEND_ELE in", values, "nodeendEle");
            return (Criteria) this;
        }

        public Criteria andNodeendEleNotIn(List<String> values) {
            addCriterion("NODEEND_ELE not in", values, "nodeendEle");
            return (Criteria) this;
        }

        public Criteria andNodeendEleBetween(String value1, String value2) {
            addCriterion("NODEEND_ELE between", value1, value2, "nodeendEle");
            return (Criteria) this;
        }

        public Criteria andNodeendEleNotBetween(String value1, String value2) {
            addCriterion("NODEEND_ELE not between", value1, value2, "nodeendEle");
            return (Criteria) this;
        }

        public Criteria andStarxEleIsNull() {
            addCriterion("STARX_ELE is null");
            return (Criteria) this;
        }

        public Criteria andStarxEleIsNotNull() {
            addCriterion("STARX_ELE is not null");
            return (Criteria) this;
        }

        public Criteria andStarxEleEqualTo(Integer value) {
            addCriterion("STARX_ELE =", value, "starxEle");
            return (Criteria) this;
        }

        public Criteria andStarxEleNotEqualTo(Integer value) {
            addCriterion("STARX_ELE <>", value, "starxEle");
            return (Criteria) this;
        }

        public Criteria andStarxEleGreaterThan(Integer value) {
            addCriterion("STARX_ELE >", value, "starxEle");
            return (Criteria) this;
        }

        public Criteria andStarxEleGreaterThanOrEqualTo(Integer value) {
            addCriterion("STARX_ELE >=", value, "starxEle");
            return (Criteria) this;
        }

        public Criteria andStarxEleLessThan(Integer value) {
            addCriterion("STARX_ELE <", value, "starxEle");
            return (Criteria) this;
        }

        public Criteria andStarxEleLessThanOrEqualTo(Integer value) {
            addCriterion("STARX_ELE <=", value, "starxEle");
            return (Criteria) this;
        }

        public Criteria andStarxEleIn(List<Integer> values) {
            addCriterion("STARX_ELE in", values, "starxEle");
            return (Criteria) this;
        }

        public Criteria andStarxEleNotIn(List<Integer> values) {
            addCriterion("STARX_ELE not in", values, "starxEle");
            return (Criteria) this;
        }

        public Criteria andStarxEleBetween(Integer value1, Integer value2) {
            addCriterion("STARX_ELE between", value1, value2, "starxEle");
            return (Criteria) this;
        }

        public Criteria andStarxEleNotBetween(Integer value1, Integer value2) {
            addCriterion("STARX_ELE not between", value1, value2, "starxEle");
            return (Criteria) this;
        }

        public Criteria andStaryEleIsNull() {
            addCriterion("STARY_ELE is null");
            return (Criteria) this;
        }

        public Criteria andStaryEleIsNotNull() {
            addCriterion("STARY_ELE is not null");
            return (Criteria) this;
        }

        public Criteria andStaryEleEqualTo(Integer value) {
            addCriterion("STARY_ELE =", value, "staryEle");
            return (Criteria) this;
        }

        public Criteria andStaryEleNotEqualTo(Integer value) {
            addCriterion("STARY_ELE <>", value, "staryEle");
            return (Criteria) this;
        }

        public Criteria andStaryEleGreaterThan(Integer value) {
            addCriterion("STARY_ELE >", value, "staryEle");
            return (Criteria) this;
        }

        public Criteria andStaryEleGreaterThanOrEqualTo(Integer value) {
            addCriterion("STARY_ELE >=", value, "staryEle");
            return (Criteria) this;
        }

        public Criteria andStaryEleLessThan(Integer value) {
            addCriterion("STARY_ELE <", value, "staryEle");
            return (Criteria) this;
        }

        public Criteria andStaryEleLessThanOrEqualTo(Integer value) {
            addCriterion("STARY_ELE <=", value, "staryEle");
            return (Criteria) this;
        }

        public Criteria andStaryEleIn(List<Integer> values) {
            addCriterion("STARY_ELE in", values, "staryEle");
            return (Criteria) this;
        }

        public Criteria andStaryEleNotIn(List<Integer> values) {
            addCriterion("STARY_ELE not in", values, "staryEle");
            return (Criteria) this;
        }

        public Criteria andStaryEleBetween(Integer value1, Integer value2) {
            addCriterion("STARY_ELE between", value1, value2, "staryEle");
            return (Criteria) this;
        }

        public Criteria andStaryEleNotBetween(Integer value1, Integer value2) {
            addCriterion("STARY_ELE not between", value1, value2, "staryEle");
            return (Criteria) this;
        }

        public Criteria andProjectidProaffIsNull() {
            addCriterion("PROJECTID_PROAFF is null");
            return (Criteria) this;
        }

        public Criteria andProjectidProaffIsNotNull() {
            addCriterion("PROJECTID_PROAFF is not null");
            return (Criteria) this;
        }

        public Criteria andProjectidProaffEqualTo(Long value) {
            addCriterion("PROJECTID_PROAFF =", value, "projectidProaff");
            return (Criteria) this;
        }

        public Criteria andProjectidProaffNotEqualTo(Integer value) {
            addCriterion("PROJECTID_PROAFF <>", value, "projectidProaff");
            return (Criteria) this;
        }

        public Criteria andProjectidProaffGreaterThan(Integer value) {
            addCriterion("PROJECTID_PROAFF >", value, "projectidProaff");
            return (Criteria) this;
        }

        public Criteria andProjectidProaffGreaterThanOrEqualTo(Integer value) {
            addCriterion("PROJECTID_PROAFF >=", value, "projectidProaff");
            return (Criteria) this;
        }

        public Criteria andProjectidProaffLessThan(Integer value) {
            addCriterion("PROJECTID_PROAFF <", value, "projectidProaff");
            return (Criteria) this;
        }

        public Criteria andProjectidProaffLessThanOrEqualTo(Integer value) {
            addCriterion("PROJECTID_PROAFF <=", value, "projectidProaff");
            return (Criteria) this;
        }

        public Criteria andProjectidProaffIn(List<Integer> values) {
            addCriterion("PROJECTID_PROAFF in", values, "projectidProaff");
            return (Criteria) this;
        }

        public Criteria andProjectidProaffNotIn(List<Integer> values) {
            addCriterion("PROJECTID_PROAFF not in", values, "projectidProaff");
            return (Criteria) this;
        }

        public Criteria andProjectidProaffBetween(Integer value1, Integer value2) {
            addCriterion("PROJECTID_PROAFF between", value1, value2, "projectidProaff");
            return (Criteria) this;
        }

        public Criteria andProjectidProaffNotBetween(Integer value1, Integer value2) {
            addCriterion("PROJECTID_PROAFF not between", value1, value2, "projectidProaff");
            return (Criteria) this;
        }

        public Criteria andLayeridEleIsNull() {
            addCriterion("LAYERID_ELE is null");
            return (Criteria) this;
        }

        public Criteria andLayeridEleIsNotNull() {
            addCriterion("LAYERID_ELE is not null");
            return (Criteria) this;
        }

        public Criteria andLayeridEleEqualTo(String value) {
            addCriterion("LAYERID_ELE =", value, "layeridEle");
            return (Criteria) this;
        }

        public Criteria andLayeridEleNotEqualTo(String value) {
            addCriterion("LAYERID_ELE <>", value, "layeridEle");
            return (Criteria) this;
        }

        public Criteria andLayeridEleGreaterThan(String value) {
            addCriterion("LAYERID_ELE >", value, "layeridEle");
            return (Criteria) this;
        }

        public Criteria andLayeridEleGreaterThanOrEqualTo(String value) {
            addCriterion("LAYERID_ELE >=", value, "layeridEle");
            return (Criteria) this;
        }

        public Criteria andLayeridEleLessThan(String value) {
            addCriterion("LAYERID_ELE <", value, "layeridEle");
            return (Criteria) this;
        }

        public Criteria andLayeridEleLessThanOrEqualTo(String value) {
            addCriterion("LAYERID_ELE <=", value, "layeridEle");
            return (Criteria) this;
        }

        public Criteria andLayeridEleLike(String value) {
            addCriterion("LAYERID_ELE like", value, "layeridEle");
            return (Criteria) this;
        }

        public Criteria andLayeridEleNotLike(String value) {
            addCriterion("LAYERID_ELE not like", value, "layeridEle");
            return (Criteria) this;
        }

        public Criteria andLayeridEleIn(List<String> values) {
            addCriterion("LAYERID_ELE in", values, "layeridEle");
            return (Criteria) this;
        }

        public Criteria andLayeridEleNotIn(List<String> values) {
            addCriterion("LAYERID_ELE not in", values, "layeridEle");
            return (Criteria) this;
        }

        public Criteria andLayeridEleBetween(String value1, String value2) {
            addCriterion("LAYERID_ELE between", value1, value2, "layeridEle");
            return (Criteria) this;
        }

        public Criteria andLayeridEleNotBetween(String value1, String value2) {
            addCriterion("LAYERID_ELE not between", value1, value2, "layeridEle");
            return (Criteria) this;
        }

        public Criteria andElementrealnameEleIsNull() {
            addCriterion("ELEMENTREALNAME_ELE is null");
            return (Criteria) this;
        }

        public Criteria andElementrealnameEleIsNotNull() {
            addCriterion("ELEMENTREALNAME_ELE is not null");
            return (Criteria) this;
        }

        public Criteria andElementrealnameEleEqualTo(String value) {
            addCriterion("ELEMENTREALNAME_ELE =", value, "elementrealnameEle");
            return (Criteria) this;
        }

        public Criteria andElementrealnameEleNotEqualTo(String value) {
            addCriterion("ELEMENTREALNAME_ELE <>", value, "elementrealnameEle");
            return (Criteria) this;
        }

        public Criteria andElementrealnameEleGreaterThan(String value) {
            addCriterion("ELEMENTREALNAME_ELE >", value, "elementrealnameEle");
            return (Criteria) this;
        }

        public Criteria andElementrealnameEleGreaterThanOrEqualTo(String value) {
            addCriterion("ELEMENTREALNAME_ELE >=", value, "elementrealnameEle");
            return (Criteria) this;
        }

        public Criteria andElementrealnameEleLessThan(String value) {
            addCriterion("ELEMENTREALNAME_ELE <", value, "elementrealnameEle");
            return (Criteria) this;
        }

        public Criteria andElementrealnameEleLessThanOrEqualTo(String value) {
            addCriterion("ELEMENTREALNAME_ELE <=", value, "elementrealnameEle");
            return (Criteria) this;
        }

        public Criteria andElementrealnameEleLike(String value) {
            addCriterion("ELEMENTREALNAME_ELE like", value, "elementrealnameEle");
            return (Criteria) this;
        }

        public Criteria andElementrealnameEleNotLike(String value) {
            addCriterion("ELEMENTREALNAME_ELE not like", value, "elementrealnameEle");
            return (Criteria) this;
        }

        public Criteria andElementrealnameEleIn(List<String> values) {
            addCriterion("ELEMENTREALNAME_ELE in", values, "elementrealnameEle");
            return (Criteria) this;
        }

        public Criteria andElementrealnameEleNotIn(List<String> values) {
            addCriterion("ELEMENTREALNAME_ELE not in", values, "elementrealnameEle");
            return (Criteria) this;
        }

        public Criteria andElementrealnameEleBetween(String value1, String value2) {
            addCriterion("ELEMENTREALNAME_ELE between", value1, value2, "elementrealnameEle");
            return (Criteria) this;
        }

        public Criteria andElementrealnameEleNotBetween(String value1, String value2) {
            addCriterion("ELEMENTREALNAME_ELE not between", value1, value2, "elementrealnameEle");
            return (Criteria) this;
        }

        public Criteria andElementtypeEleIsNull() {
            addCriterion("ELEMENTTYPE_ELE is null");
            return (Criteria) this;
        }

        public Criteria andElementtypeEleIsNotNull() {
            addCriterion("ELEMENTTYPE_ELE is not null");
            return (Criteria) this;
        }

        public Criteria andElementtypeEleEqualTo(String value) {
            addCriterion("ELEMENTTYPE_ELE =", value, "elementtypeEle");
            return (Criteria) this;
        }

        public Criteria andElementtypeEleNotEqualTo(String value) {
            addCriterion("ELEMENTTYPE_ELE <>", value, "elementtypeEle");
            return (Criteria) this;
        }

        public Criteria andElementtypeEleGreaterThan(String value) {
            addCriterion("ELEMENTTYPE_ELE >", value, "elementtypeEle");
            return (Criteria) this;
        }

        public Criteria andElementtypeEleGreaterThanOrEqualTo(String value) {
            addCriterion("ELEMENTTYPE_ELE >=", value, "elementtypeEle");
            return (Criteria) this;
        }

        public Criteria andElementtypeEleLessThan(String value) {
            addCriterion("ELEMENTTYPE_ELE <", value, "elementtypeEle");
            return (Criteria) this;
        }

        public Criteria andElementtypeEleLessThanOrEqualTo(String value) {
            addCriterion("ELEMENTTYPE_ELE <=", value, "elementtypeEle");
            return (Criteria) this;
        }

        public Criteria andElementtypeEleLike(String value) {
            addCriterion("ELEMENTTYPE_ELE like", value, "elementtypeEle");
            return (Criteria) this;
        }

        public Criteria andElementtypeEleNotLike(String value) {
            addCriterion("ELEMENTTYPE_ELE not like", value, "elementtypeEle");
            return (Criteria) this;
        }

        public Criteria andElementtypeEleIn(List<String> values) {
            addCriterion("ELEMENTTYPE_ELE in", values, "elementtypeEle");
            return (Criteria) this;
        }

        public Criteria andElementtypeEleNotIn(List<String> values) {
            addCriterion("ELEMENTTYPE_ELE not in", values, "elementtypeEle");
            return (Criteria) this;
        }

        public Criteria andElementtypeEleBetween(String value1, String value2) {
            addCriterion("ELEMENTTYPE_ELE between", value1, value2, "elementtypeEle");
            return (Criteria) this;
        }

        public Criteria andElementtypeEleNotBetween(String value1, String value2) {
            addCriterion("ELEMENTTYPE_ELE not between", value1, value2, "elementtypeEle");
            return (Criteria) this;
        }

        public Criteria andElementisstateIsNull() {
            addCriterion("ELEMENTISSTATE is null");
            return (Criteria) this;
        }

        public Criteria andElementisstateIsNotNull() {
            addCriterion("ELEMENTISSTATE is not null");
            return (Criteria) this;
        }

        public Criteria andElementisstateEqualTo(Integer value) {
            addCriterion("ELEMENTISSTATE =", value, "elementisstate");
            return (Criteria) this;
        }

        public Criteria andElementisstateNotEqualTo(Integer value) {
            addCriterion("ELEMENTISSTATE <>", value, "elementisstate");
            return (Criteria) this;
        }

        public Criteria andElementisstateGreaterThan(Integer value) {
            addCriterion("ELEMENTISSTATE >", value, "elementisstate");
            return (Criteria) this;
        }

        public Criteria andElementisstateGreaterThanOrEqualTo(Integer value) {
            addCriterion("ELEMENTISSTATE >=", value, "elementisstate");
            return (Criteria) this;
        }

        public Criteria andElementisstateLessThan(Integer value) {
            addCriterion("ELEMENTISSTATE <", value, "elementisstate");
            return (Criteria) this;
        }

        public Criteria andElementisstateLessThanOrEqualTo(Integer value) {
            addCriterion("ELEMENTISSTATE <=", value, "elementisstate");
            return (Criteria) this;
        }

        public Criteria andElementisstateIn(List<Integer> values) {
            addCriterion("ELEMENTISSTATE in", values, "elementisstate");
            return (Criteria) this;
        }

        public Criteria andElementisstateNotIn(List<Integer> values) {
            addCriterion("ELEMENTISSTATE not in", values, "elementisstate");
            return (Criteria) this;
        }

        public Criteria andElementisstateBetween(Integer value1, Integer value2) {
            addCriterion("ELEMENTISSTATE between", value1, value2, "elementisstate");
            return (Criteria) this;
        }

        public Criteria andElementisstateNotBetween(Integer value1, Integer value2) {
            addCriterion("ELEMENTISSTATE not between", value1, value2, "elementisstate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ELEMENT_TBL
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 13 18:21:09 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ELEMENT_TBL
     *
     * @mbggenerated Wed Nov 13 18:21:09 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}