package com.ywjs.model.entity;

import java.io.Serializable;

public class EletypeProperty implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ELETYPE_PROPERTY_TBL.ELEPROID_ELEPRO
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    private Integer eleproidElepro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ELETYPE_PROPERTY_TBL.PROPERTYID_PRO
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    private Integer propertyidPro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ELETYPE_PROPERTY_TBL.ELETYPE_ELEPRO
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    private String eletypeElepro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ELETYPE_PROPERTY_TBL.ELETYPE_NUMBER_ELEPRO
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    private Integer eletypeNumberElepro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ELETYPE_PROPERTY_TBL
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ELETYPE_PROPERTY_TBL.ELEPROID_ELEPRO
     *
     * @return the value of ELETYPE_PROPERTY_TBL.ELEPROID_ELEPRO
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    public Integer getEleproidElepro() {
        return eleproidElepro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ELETYPE_PROPERTY_TBL.ELEPROID_ELEPRO
     *
     * @param eleproidElepro the value for ELETYPE_PROPERTY_TBL.ELEPROID_ELEPRO
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    public void setEleproidElepro(Integer eleproidElepro) {
        this.eleproidElepro = eleproidElepro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ELETYPE_PROPERTY_TBL.PROPERTYID_PRO
     *
     * @return the value of ELETYPE_PROPERTY_TBL.PROPERTYID_PRO
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    public Integer getPropertyidPro() {
        return propertyidPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ELETYPE_PROPERTY_TBL.PROPERTYID_PRO
     *
     * @param propertyidPro the value for ELETYPE_PROPERTY_TBL.PROPERTYID_PRO
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    public void setPropertyidPro(Integer propertyidPro) {
        this.propertyidPro = propertyidPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ELETYPE_PROPERTY_TBL.ELETYPE_ELEPRO
     *
     * @return the value of ELETYPE_PROPERTY_TBL.ELETYPE_ELEPRO
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    public String getEletypeElepro() {
        return eletypeElepro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ELETYPE_PROPERTY_TBL.ELETYPE_ELEPRO
     *
     * @param eletypeElepro the value for ELETYPE_PROPERTY_TBL.ELETYPE_ELEPRO
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    public void setEletypeElepro(String eletypeElepro) {
        this.eletypeElepro = eletypeElepro == null ? null : eletypeElepro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ELETYPE_PROPERTY_TBL.ELETYPE_NUMBER_ELEPRO
     *
     * @return the value of ELETYPE_PROPERTY_TBL.ELETYPE_NUMBER_ELEPRO
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    public Integer getEletypeNumberElepro() {
        return eletypeNumberElepro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ELETYPE_PROPERTY_TBL.ELETYPE_NUMBER_ELEPRO
     *
     * @param eletypeNumberElepro the value for ELETYPE_PROPERTY_TBL.ELETYPE_NUMBER_ELEPRO
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    public void setEletypeNumberElepro(Integer eletypeNumberElepro) {
        this.eletypeNumberElepro = eletypeNumberElepro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ELETYPE_PROPERTY_TBL
     *
     * @mbggenerated Tue Nov 12 19:05:36 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", eleproidElepro=").append(eleproidElepro);
        sb.append(", propertyidPro=").append(propertyidPro);
        sb.append(", eletypeElepro=").append(eletypeElepro);
        sb.append(", eletypeNumberElepro=").append(eletypeNumberElepro);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}