package com.ywjs.model.query;

import java.util.Date;
/**
 * 
 * @ClassName Project
 * @Description TODO(工程表实体类) 
 * @Author 周伟
 * @Date 2019年11月11日 下午5:29:54
 */
public class QueryProject extends QueryBase {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT_TBL.PROJECTID_PRO
     *
     * @mbggenerated Mon Nov 11 17:29:10 CST 2019
     */
    private Integer projectidPro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT_TBL.PROJECTNAME_PRO
     *
     * @mbggenerated Mon Nov 11 17:29:10 CST 2019
     */
    private String projectnamePro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT_TBL.CREATEDATE_PRO
     *
     * @mbggenerated Mon Nov 11 17:29:10 CST 2019
     */
    private Date createdatePro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT_TBL.PROUSERNAME_PRO
     *
     * @mbggenerated Mon Nov 11 17:29:10 CST 2019
     */
    private String prousernamePro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROJECT_TBL.REMARK_PRO
     *
     * @mbggenerated Mon Nov 11 17:29:10 CST 2019
     */
    private String remarkPro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PROJECT_TBL
     *
     * @mbggenerated Mon Nov 11 17:29:10 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT_TBL.PROJECTID_PRO
     *
     * @return the value of PROJECT_TBL.PROJECTID_PRO
     *
     * @mbggenerated Mon Nov 11 17:29:10 CST 2019
     */
    public Integer getProjectidPro() {
        return projectidPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT_TBL.PROJECTID_PRO
     *
     * @param projectidPro the value for PROJECT_TBL.PROJECTID_PRO
     *
     * @mbggenerated Mon Nov 11 17:29:10 CST 2019
     */
    public void setProjectidPro(Integer projectidPro) {
        this.projectidPro = projectidPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT_TBL.PROJECTNAME_PRO
     *
     * @return the value of PROJECT_TBL.PROJECTNAME_PRO
     *
     * @mbggenerated Mon Nov 11 17:29:10 CST 2019
     */
    public String getProjectnamePro() {
        return projectnamePro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT_TBL.PROJECTNAME_PRO
     *
     * @param projectnamePro the value for PROJECT_TBL.PROJECTNAME_PRO
     *
     * @mbggenerated Mon Nov 11 17:29:10 CST 2019
     */
    public void setProjectnamePro(String projectnamePro) {
        this.projectnamePro = projectnamePro == null ? null : projectnamePro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT_TBL.CREATEDATE_PRO
     *
     * @return the value of PROJECT_TBL.CREATEDATE_PRO
     *
     * @mbggenerated Mon Nov 11 17:29:10 CST 2019
     */
    public Date getCreatedatePro() {
        return createdatePro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT_TBL.CREATEDATE_PRO
     *
     * @param createdatePro the value for PROJECT_TBL.CREATEDATE_PRO
     *
     * @mbggenerated Mon Nov 11 17:29:10 CST 2019
     */
    public void setCreatedatePro(Date createdatePro) {
        this.createdatePro = createdatePro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT_TBL.PROUSERNAME_PRO
     *
     * @return the value of PROJECT_TBL.PROUSERNAME_PRO
     *
     * @mbggenerated Mon Nov 11 17:29:10 CST 2019
     */
    public String getProusernamePro() {
        return prousernamePro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT_TBL.PROUSERNAME_PRO
     *
     * @param prousernamePro the value for PROJECT_TBL.PROUSERNAME_PRO
     *
     * @mbggenerated Mon Nov 11 17:29:10 CST 2019
     */
    public void setProusernamePro(String prousernamePro) {
        this.prousernamePro = prousernamePro == null ? null : prousernamePro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROJECT_TBL.REMARK_PRO
     *
     * @return the value of PROJECT_TBL.REMARK_PRO
     *
     * @mbggenerated Mon Nov 11 17:29:10 CST 2019
     */
    public String getRemarkPro() {
        return remarkPro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROJECT_TBL.REMARK_PRO
     *
     * @param remarkPro the value for PROJECT_TBL.REMARK_PRO
     *
     * @mbggenerated Mon Nov 11 17:29:10 CST 2019
     */
    public void setRemarkPro(String remarkPro) {
        this.remarkPro = remarkPro == null ? null : remarkPro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PROJECT_TBL
     *
     * @mbggenerated Mon Nov 11 17:29:10 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", projectidPro=").append(projectidPro);
        sb.append(", projectnamePro=").append(projectnamePro);
        sb.append(", createdatePro=").append(createdatePro);
        sb.append(", prousernamePro=").append(prousernamePro);
        sb.append(", remarkPro=").append(remarkPro);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}